name: Python Code Quality & Type Checking

on:
  pull_request:
    paths:
      - 'src/python/**'
      - '.github/workflows/python-lint.yml'

jobs:
  ruff-mypy-check:
    name: Ruff Linting, Formatting & MyPy Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/python
        pip install -e ".[dev]"
        
    - name: Run ruff linter
      run: |
        cd src/python
        ruff check .
        
    - name: Run ruff formatter check
      run: |
        cd src/python
        ruff format --check .

    - name: Run mypy type checking
      run: |
        cd src/python
        mypy

    - name: Run mypy type checker
      run: |
        cd src/python
        mypy .
