name: Python Code Quality

on:
  pull_request:
    paths:
      - 'src/python/**'
      - '.github/workflows/python-lint.yml'

jobs:
  ruff-check:
    name: Ruff Linting & Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.12.11
        
    - name: Run ruff linter
      run: |
        cd src/python
        ruff check .
        
    - name: Run ruff formatter check
      run: |
        cd src/python
        ruff format --check .
